"""
Detection pipeline tests (Prompt 6).

Runs against the synthetic sample floor plan images in data/samples/
(generated by scripts/generate_sample_floorplans.py -- see that script's
docstring for why synthetic fixtures are used instead of real scans).

Covers preprocessing, wall/room/opening/stair detection, OCR + association,
postprocessing/calibration, and the full assembled pipeline validated
against the real Prompt 4 schema validator (not a reimplementation of it).
"""
import math
from pathlib import Path

import cv2
import numpy as np
import pytest

from app.cv import detector, postprocessing, preprocessing
from app.floorplan.validator import validate_floorplan
from app.ocr import ocr_service

REPO_ROOT = Path(__file__).resolve().parents[2]
SAMPLES_DIR = REPO_ROOT / "data" / "samples"
COTTAGE_PATH = SAMPLES_DIR / "sample_floorplan_cottage.png"
STUDIO_PATH = SAMPLES_DIR / "sample_floorplan_studio.png"


@pytest.fixture(scope="module")
def cottage_preprocessed():
    assert COTTAGE_PATH.exists(), "Run scripts/generate_sample_floorplans.py first"
    return preprocessing.preprocess(COTTAGE_PATH)


@pytest.fixture(scope="module")
def studio_preprocessed():
    assert STUDIO_PATH.exists(), "Run scripts/generate_sample_floorplans.py first"
    return preprocessing.preprocess(STUDIO_PATH)


# --- Preprocessing -----------------------------------------------------------


def test_sample_images_exist():
    assert COTTAGE_PATH.exists()
    assert STUDIO_PATH.exists()


def test_preprocess_produces_binary_image(cottage_preprocessed):
    img = cottage_preprocessed.working_image
    assert img.dtype == np.uint8
    unique_values = set(np.unique(img).tolist())
    assert unique_values.issubset({0, 255})


def test_preprocess_respects_working_resolution_bounds(cottage_preprocessed):
    w, h = cottage_preprocessed.working_size
    assert preprocessing.WORKING_LONG_EDGE_MIN <= max(w, h) <= preprocessing.WORKING_LONG_EDGE_MAX


def test_preprocess_rejects_unsupported_extension(tmp_path):
    fake_file = tmp_path / "not_a_floorplan.txt"
    fake_file.write_text("hello")
    with pytest.raises(preprocessing.UnsupportedFileError):
        preprocessing.load_image(fake_file)


def test_preprocess_rejects_missing_file():
    with pytest.raises(FileNotFoundError):
        preprocessing.load_image("/tmp/does_not_exist_12345.png")


# --- Wall detection -----------------------------------------------------------


def test_detect_walls_finds_expected_count_on_cottage(cottage_preprocessed):
    walls, openings, thin_lines = detector.detect_walls(cottage_preprocessed.working_image)
    # 4 exterior perimeter walls + 1 interior dividing wall
    assert len(walls) == 5
    assert sum(1 for w in walls if w.wall_type == "exterior") == 4
    assert sum(1 for w in walls if w.wall_type == "interior") == 1


def test_detect_walls_finds_expected_count_on_studio(studio_preprocessed):
    walls, openings, thin_lines = detector.detect_walls(studio_preprocessed.working_image)
    assert len(walls) == 4
    assert all(w.wall_type == "exterior" for w in walls)


def test_thin_dimension_line_excluded_from_walls(cottage_preprocessed):
    """The 1px dimension line under the building must not be reported as a wall."""
    walls, openings, thin_lines = detector.detect_walls(cottage_preprocessed.working_image)
    for wall in walls:
        assert wall.thickness_px >= detector.MIN_WALL_THICKNESS_PX
    # ...but it should still be captured as dimension-line candidate geometry.
    assert len(thin_lines) >= 1


def test_interior_wall_classified_correctly_despite_spanning_most_of_the_height(cottage_preprocessed):
    """
    Regression test: an earlier version of classify_exterior_interior checked
    a wall's coordinates against ALL four boundary extents rather than just
    its own perpendicular axis, which misclassified the interior dividing
    wall (it spans nearly the full building height, like real exterior walls
    do) as exterior.
    """
    walls, openings, thin_lines = detector.detect_walls(cottage_preprocessed.working_image)
    interior_walls = [w for w in walls if w.wall_type == "interior"]
    assert len(interior_walls) == 1
    assert interior_walls[0].orientation == "vertical"


def test_nearby_offsets_straddling_bucket_boundary_still_merge():
    """
    Regression test: naive round(offset / tolerance) bucketing split two
    genuinely close line offsets (e.g. 682.0 and 684.3 with tolerance=8)
    into separate walls because they rounded to different buckets. Chained
    proximity clustering must not have this failure mode.
    """
    close_segments = [
        detector.RawSegment(10.0, 682.0, 10.0, 700.0),
        detector.RawSegment(10.0, 684.3, 10.0, 720.0),
    ]
    groups = detector._cluster_by_proximity(close_segments, lambda s: s.x1, tolerance=8.0)
    assert len(groups) == 1


# --- Room detection -----------------------------------------------------------


def test_detect_rooms_finds_two_rooms_on_cottage(cottage_preprocessed):
    walls, openings, thin_lines = detector.detect_walls(cottage_preprocessed.working_image)
    rooms = detector.detect_rooms(walls, cottage_preprocessed.working_image.shape)
    assert len(rooms) == 2


def test_detect_rooms_finds_one_room_on_studio(studio_preprocessed):
    walls, openings, thin_lines = detector.detect_walls(studio_preprocessed.working_image)
    rooms = detector.detect_rooms(walls, studio_preprocessed.working_image.shape)
    assert len(rooms) == 1


def test_room_hierarchy_artifact_not_counted_as_extra_room(cottage_preprocessed):
    """
    Regression test: RETR_CCOMP produces a 'hole' contour representing the
    building's wall silhouette as a child of the background contour. An
    earlier version counted this as a spurious third room.
    """
    walls, openings, thin_lines = detector.detect_walls(cottage_preprocessed.working_image)
    rooms = detector.detect_rooms(walls, cottage_preprocessed.working_image.shape)
    assert len(rooms) == 2, "A hierarchy artifact should not be counted as a room"


def test_room_polygons_have_at_least_three_points(cottage_preprocessed):
    walls, openings, thin_lines = detector.detect_walls(cottage_preprocessed.working_image)
    rooms = detector.detect_rooms(walls, cottage_preprocessed.working_image.shape)
    for room in rooms:
        assert len(room.polygon_px) >= 3


# --- Door / window detection ---------------------------------------------------


def test_exterior_door_detected_with_swing(cottage_preprocessed):
    img = cottage_preprocessed.working_image
    walls, opening_candidates, thin_lines = detector.detect_walls(img)
    all_segments = detector.detect_fine_segments_for_leaf_search(img)
    openings = detector.detect_openings(walls, opening_candidates, all_segments)

    doors_with_swing = [o for o in openings if o.kind == "door" and o.swing_detected]
    assert len(doors_with_swing) >= 1


def test_cottage_has_two_doors_and_one_window(cottage_preprocessed):
    img = cottage_preprocessed.working_image
    walls, opening_candidates, thin_lines = detector.detect_walls(img)
    all_segments = detector.detect_fine_segments_for_leaf_search(img)
    openings = detector.detect_openings(walls, opening_candidates, all_segments)
    openings = postprocessing.suppress_duplicate_openings(openings)

    doors = [o for o in openings if o.kind == "door"]
    windows = [o for o in openings if o.kind == "window"]
    assert len(doors) == 2  # exterior entry + interior connecting door
    assert len(windows) == 1


def test_studio_door_detected(studio_preprocessed):
    img = studio_preprocessed.working_image
    walls, opening_candidates, thin_lines = detector.detect_walls(img)
    all_segments = detector.detect_fine_segments_for_leaf_search(img)
    openings = detector.detect_openings(walls, opening_candidates, all_segments)
    assert len(openings) == 1
    assert openings[0].kind == "door"


# --- Stair detection -----------------------------------------------------------


def test_stair_detected_on_cottage(cottage_preprocessed):
    img = cottage_preprocessed.working_image
    walls, opening_candidates, thin_lines = detector.detect_walls(img)
    wall_mask = detector.isolate_wall_mask(img)
    stairs = detector.detect_stairs(img, wall_mask)
    assert len(stairs) == 1


def test_no_stairs_on_studio(studio_preprocessed):
    img = studio_preprocessed.working_image
    wall_mask = detector.isolate_wall_mask(img)
    stairs = detector.detect_stairs(img, wall_mask)
    assert len(stairs) == 0


def test_ocr_text_does_not_produce_false_stair_detection(cottage_preprocessed):
    """
    Regression test: room-label text ('Living Room', 'Bedroom') sitting at a
    consistent y-height was originally clustered by the stair heuristic into
    a false-positive stair region spanning almost the full building width.
    """
    img = cottage_preprocessed.working_image
    wall_mask = detector.isolate_wall_mask(img)
    stairs = detector.detect_stairs(img, wall_mask)
    for stair in stairs:
        xs = [p[0] for p in stair.polygon_px]
        width = max(xs) - min(xs)
        assert width <= detector.STAIR_MAX_ALONG_EXTENT_PX


# --- OCR ------------------------------------------------------------------


def test_ocr_extracts_room_labels_and_dimension(cottage_preprocessed):
    blocks = ocr_service.extract_text_blocks(cottage_preprocessed.grayscale_image)
    texts = [b.text for b in blocks]
    assert any("Living" in t and "Room" in t for t in texts)
    assert any("Bedroom" in t for t in texts)
    assert any("24" in t for t in texts)


def test_ocr_backend_is_reported(cottage_preprocessed):
    ocr_service.extract_text_blocks(cottage_preprocessed.grayscale_image)
    backend = ocr_service.get_ocr_backend_name()
    assert backend in ("easyocr", "tesseract", "none")


def test_multiword_room_label_not_fragmented(cottage_preprocessed):
    """
    Regression test: Tesseract returns per-word boxes; an earlier version
    treated each word as its own block, so 'Living Room' (two words) never
    matched the 'living room' keyword phrase as a whole.
    """
    blocks = ocr_service.extract_text_blocks(cottage_preprocessed.grayscale_image)
    classified = ocr_service.classify_text_blocks(blocks)
    room_labels = [c for c in classified if c.kind == "room_label"]
    assert any(c.block.text.strip().lower() == "living room" for c in room_labels)


def test_same_row_labels_not_merged_into_one_block(cottage_preprocessed):
    """
    Regression test: Tesseract's own line-grouping merged 'Living Room' and
    'Bedroom' into a single line because they sit at the same y-height. The
    large horizontal gap between them must cause a split.
    """
    blocks = ocr_service.extract_text_blocks(cottage_preprocessed.grayscale_image)
    classified = ocr_service.classify_text_blocks(blocks)
    room_labels = [c for c in classified if c.kind == "room_label"]
    label_texts = {c.block.text.strip().lower() for c in room_labels}
    assert "living room" in label_texts
    assert "bedroom" in label_texts
    assert "living room bedroom" not in label_texts


def test_dimension_pattern_parses_common_formats():
    assert ocr_service._parse_dimension_value("24 ft") == 24.0
    assert ocr_service._parse_dimension_value("24") == 24.0
    assert ocr_service._parse_dimension_value("3.5m") == 3.5
    assert ocr_service._parse_dimension_value("12'-6\"") == pytest.approx(12.5, abs=0.01)
    assert ocr_service._parse_dimension_value("Bedroom") is None


def test_room_label_association_by_point_in_polygon(cottage_preprocessed):
    img = cottage_preprocessed.working_image
    walls, opening_candidates, thin_lines = detector.detect_walls(img)
    rooms = detector.detect_rooms(walls, img.shape)
    room_dicts = [{"id": r.id, "polygon_px": r.polygon_px} for r in rooms]

    blocks = ocr_service.extract_text_blocks(cottage_preprocessed.grayscale_image)
    classified = ocr_service.classify_text_blocks(blocks)
    ocr_service.associate_room_labels(room_dicts, classified)

    names = {rd.get("name") for rd in room_dicts}
    assert "Living Room" in names
    assert "Bedroom" in names


def test_dimension_matched_to_thin_line_geometry(cottage_preprocessed):
    img = cottage_preprocessed.working_image
    walls, opening_candidates, thin_lines = detector.detect_walls(img)
    blocks = ocr_service.extract_text_blocks(cottage_preprocessed.grayscale_image)
    classified = ocr_service.classify_text_blocks(blocks)
    dims = ocr_service.associate_dimensions(classified, thin_lines)

    assert len(dims) == 1
    assert dims[0]["value"] == 24.0
    assert dims[0]["matched_to_geometry"] is True


# --- Postprocessing / calibration ----------------------------------------------


def test_calibration_prefers_ocr_match_over_fallback():
    result = postprocessing.calibrate_scale([(24.0, 480.0)], fallback_reference_px_length=999.0)
    assert result.source == "ocr_dimension_match"
    assert result.pixels_per_unit == pytest.approx(20.0)
    assert result.note is None


def test_calibration_falls_back_when_no_dimension_matched():
    result = postprocessing.calibrate_scale([], fallback_reference_px_length=600.0)
    assert result.source == "fallback_default_assumption"
    assert result.note is not None
    assert result.pixels_per_unit == pytest.approx(600.0 / postprocessing.FALLBACK_ASSUMED_WIDTH_UNITS)


def test_calibration_last_resort_when_nothing_available():
    result = postprocessing.calibrate_scale([], fallback_reference_px_length=None)
    assert result.source == "fallback_default_assumption"
    assert result.pixels_per_unit == 1.0
    assert "uncalibrated" in result.note


def test_wall_confidence_within_valid_range(cottage_preprocessed):
    walls, openings, thin_lines = detector.detect_walls(cottage_preprocessed.working_image)
    for wall in walls:
        confidence = postprocessing.score_wall_confidence(wall)
        assert 0.0 <= confidence <= 1.0


def test_opening_confidence_uses_tier2_ceiling():
    swing_opening = detector.OpeningDetection(
        id="door-x", kind="door", wall_id="wall-x", position=0.5, width_px=60, swing_detected=True
    )
    no_swing_opening = detector.OpeningDetection(
        id="door-y", kind="door", wall_id="wall-x", position=0.5, width_px=60, swing_detected=False
    )
    assert postprocessing.score_opening_confidence(swing_opening) < 1.0
    assert postprocessing.score_opening_confidence(no_swing_opening) < postprocessing.score_opening_confidence(swing_opening)


# --- Full pipeline / schema validation (end-to-end) ----------------------------


def test_full_pipeline_produces_schema_valid_floorplan_for_cottage():
    fp_dict = detector.run_detection_pipeline(str(COTTAGE_PATH), "TEST-COTTAGE")
    result = validate_floorplan(fp_dict)
    assert result.is_valid, result.errors


def test_full_pipeline_produces_schema_valid_floorplan_for_studio():
    fp_dict = detector.run_detection_pipeline(str(STUDIO_PATH), "TEST-STUDIO")
    result = validate_floorplan(fp_dict)
    assert result.is_valid, result.errors


def test_full_pipeline_every_element_has_confidence_and_source():
    fp_dict = detector.run_detection_pipeline(str(COTTAGE_PATH), "TEST-COTTAGE")
    for collection in ("rooms", "walls", "doors", "windows", "stairs", "dimensions"):
        for element in fp_dict[collection]:
            assert element["source"] == "ai_detection"
            assert element["confidence"] is not None
            assert 0.0 <= element["confidence"] <= 1.0


def test_full_pipeline_dimension_calibration_is_reasonably_accurate():
    """
    The cottage is drawn as a 24ft-wide building with an OCR-readable '24 ft'
    label. After calibration, the detected building width (max_x - min_x
    across wall endpoints) should be close to 24 units -- not exact, given
    Hough imprecision, but within a generous tolerance.
    """
    fp_dict = detector.run_detection_pipeline(str(COTTAGE_PATH), "TEST-COTTAGE")
    xs = [pt["x"] for wall in fp_dict["walls"] for pt in (wall["start"], wall["end"])]
    detected_width = max(xs) - min(xs)
    assert detected_width == pytest.approx(24.0, abs=2.0)


def test_full_pipeline_furniture_always_empty():
    fp_dict = detector.run_detection_pipeline(str(COTTAGE_PATH), "TEST-COTTAGE")
    assert fp_dict["furniture"] == []


def test_full_pipeline_metadata_populated():
    fp_dict = detector.run_detection_pipeline(str(COTTAGE_PATH), "TEST-COTTAGE")
    meta = fp_dict["metadata"]
    assert meta["detection_version"] is not None
    assert meta["source_image_reference"] == str(COTTAGE_PATH)
    assert "calibration_source" in meta["extra"]


def test_full_pipeline_door_and_window_height_fields_always_null():
    """
    Regression / design-fidelity test: per DETECTION_PIPELINE.md Section 5,
    vertical dimensions (height, sill_height) are not visible in a top-down
    2D plan and must never be populated by this pipeline.
    """
    fp_dict = detector.run_detection_pipeline(str(COTTAGE_PATH), "TEST-COTTAGE")
    for door in fp_dict["doors"]:
        assert door["height"] is None
    for window in fp_dict["windows"]:
        assert window["height"] is None
        assert window["sill_height"] is None
    for wall in fp_dict["walls"]:
        assert wall["height"] is None


def test_full_pipeline_rejects_unsupported_file(tmp_path):
    fake_file = tmp_path / "not_a_plan.txt"
    fake_file.write_text("nope")
    with pytest.raises(preprocessing.UnsupportedFileError):
        detector.run_detection_pipeline(str(fake_file), "TEST-BAD")
